// Titres des chapitres - Bible Chantee
const chapterTitles = {
    "01": {
        1: "\"Création de Lumière\"",
        2: "\"Création d'Amour\"",
        3: "\"Dans la Lumière de Ta Vérité\"",
        4: "\"Miséricorde dans la Chute\"",
        5: "\"Promesse de Vie\"",
        6: "\"Grâce au Milieu du Déluge\"",
        7: "\"Refuge de Grâce\"",
        8: "\"Promesse de Vie\"",
        9: "\"Promesse Éternelle\"",
        10: "\"Chanson des Nations\"",
        11: "\"Unis dans ta Lumière\"",
        12: "\"Vers la Promesse\"",
        13: "\"Regarde et Sois Béni\"",
        14: "\"Vainqueur par Ta Grâce\"",
        15: "Étoiles de Promesse",
        16: "\"Le Dieu qui Voit\"",
        17: "\"Alliance Éternelle\"",
        18: "\"Seigneur, Reste Avec Moi\"",
        19: "\"Refuge dans la Tempête\"",
        20: "\"Dieu de Protection et de Vérité\"",
        21: "\"Promesse de Joie\"",
        22: "\"À la Montagne de l'Éternel\"",
        23: "\"Le Sépulcre de l'Amour\"",
        24: "\"Guidés par Ta Promesse\"",
        25: "\"Fidélité à Travers les Générations\"",
        26: "\"Ma Lumière dans la Famine\"",
        27: "\"Dans l'Ombre de la Bénédiction\"",
        28: "\"Dans Ta Lumière, Ô Dieu\"",
        29: "\"Dans les Chemins de la Grâce\"",
        30: "\"Dans Tes Mains, Ô Éternel\"",
        31: "\"Retour vers la Lumière\"",
        32: "\"Vainqueur par Sa Grâce\"",
        33: "\"Dans Tes Bras, Seigneur\"",
        34: "\"Justice et Pardon\"",
        35: "\"À Béthel, je Te célèbre\"",
        36: "\"Héritage de Louange\"",
        37: "\"Dans l'Ombre, Ta Lumière\"",
        38: "\"Lumière dans l'Obscurité\"",
        39: "\"Fidèle comme Joseph\"",
        40: "\"Dans l'Ombre, Ta Lumière\"",
        41: "\"Révélations de l'Abondance\"",
        42: "\"Vers la Lumière de l'Égypte\"",
        43: "\"Rassemble-nous dans Ta grâce\"",
        44: "\"Le Sacrifice de l'Amour\"",
        45: "\"Joseph, le Sauveur de nos Cœurs\"",
        46: "\"Dans Ta Présence, Seigneur\"",
        47: "\"Dans le Pays de Gosen\"",
        48: "\"Bénis Nos Enfants\"",
        49: "\"Les Bénédictions de Jacob\"",
        50: "\"Dieu de Miséricorde\"",
    },
    "02": {
        1: "\"Force et Multiplication\"",
        2: "\"Échos de Rédemption\"",
        3: "« Je suis Celui qui suis »",
        4: "\"Dieu Est Avec Toi\"",
        5: "\"Liberté pour Mon Peuple\"",
        6: "\"Libérés par Ta Force\"",
        7: "\"Libération par Ta Puissance\"",
        8: "\"Libère Ton Peuple, Ô Éternel\"",
        9: "\"Éternel, Notre Force\"",
        10: "\"Libérés par Ta Puissance\"",
        11: "\"Libération Annoncée\"",
        12: "\"Le Sang de la Pâque\"",
        13: "\"Par Ta Main Puissante\"",
        14: "\"Au Cœur de la Mer, Notre Délivrance\"",
        15: "\"Éternel, Vaillant Guerrier\"",
        16: "\"Pain du Ciel, Notre Nourriture\"",
        17: "\"Notre Rocher, notre Victoire\"",
        18: "\"Libération et Sagesse\"",
        19: "\"Peuple de l'Éternel\"",
        20: "\"Éternel, Mon Dieu et Mon Soleil\"",
        21: "\"Liberté et Amour\"",
        22: "\"Justice et Miséricorde\"",
        23: "\"Ensemble dans Ta Vérité\"",
        24: "\"Au Pied de la Montagne\"",
        25: "\"Sanctuaire de Lumière\"",
        26: "\"Dans le Lieu Très Saint\"",
        27: "\"Dans le Parvis de Ta Gloire\"",
        28: "\"Vêtus de Sa Gloire\"",
        29: "\"Sanctifiés pour Ta Gloire\"",
        30: "\"Parfum d'Adoration\"",
        31: "\"Artisans de Ta Gloire\"",
        32: "\"Rappelle-nous à Toi, Éternel\"",
        33: "\"Marche avec Nous, Ô Éternel\"",
        34: "\"Rayonnement de Ta Grâce\"",
        35: "\"Offrande de Louange\"",
        36: "\"Ensemble, Bâtissons pour Sa Gloire\"",
        37: "\"Dans le Saint des Saints\"",
        38: "\"Dans le Parvis de Ta Gloire\"",
        39: "\"Trésor de Gloire\"",
        40: "\"Dans Ta Gloire, Éternel\"",
    },
    "03": {
        1: "\"Un Parfum d'Offrande\"",
        2: "\"Odeurs de Louanges\"",
        3: "\"Au Feu de Ta Grâce\"",
        4: "\"Dans Ta Lumière, Nous Marchons\"",
        5: "\"Ton Amour, Notre Rédemption\"",
        6: "\"Reviens à Ton Éternel\"",
        7: "\"Offrande de Grâce\"",
        8: "\"Consacrés pour Ta Gloire\"",
        9: "\"Feu de Gloire\"",
        10: "\"Sanctifié devant Toi\"",
        11: "\"Purifiés par Ta Sainteté\"",
        12: "\"Purifiés par Ta Grâce\"",
        13: "\"Guéris-moi, Éternel\"",
        14: "\"Purifié par Ta Grâce\"",
        15: "\"Purifiés par Ta Grâce\"",
        16: "\"Jour d'Expiation, Grâce Éternelle\"",
        17: "\"Notre Sang, Notre Sacrifice\"",
        18: "\"Dans Ta Lumière, Éternel\"",
        19: "\"Soyez Saints, Éternel est Saint\"",
        20: "\"Sanctifiés pour l'Éternel\"",
        21: "\"Saint, Saint, Éternel!\"",
        22: "\"Sanctifiés par Ta Grâce\"",
        23: "\"Fêtes de Louange\"",
        24: "\"Brille, Ô Lumière de Justice\"",
        25: "« Le Jubilé de la Liberté »",
        26: "\"Éternel, Notre Liberté\"",
        27: "\"Consacrés à Toi, Éternel\"",
    },
    "04": {
        1: "\"Comptés sous ta Lumière\"",
        2: "\"Unis sous Ta Lumière\"",
        3: "\"Serviteurs de Ta Gloire\"",
        4: "\"Serviteurs de Sa Gloire\"",
        5: "\"Dans Ta Présence, Seigneur\"",
        6: "\"Consacrés pour Ta Gloire\"",
        7: "\"Offrandes de Louange\"",
        8: "\"Consacrés pour Ta Gloire\"",
        9: "\"Dans la Lumière de Ta Promesse\"",
        10: "\"Sonnez, Ô Trompettes!\"",
        11: "\"Écoute notre cri, ô Éternel\"",
        12: "\"Éternel, notre Guide\"",
        13: "\"Vers la Terre Promise\"",
        14: "\"Ne Crains Pas, Je Suis Avec Toi\"",
        15: "\"Offrandes de Louange\"",
        16: "\"Dans Ta Gloire, Éternel\"",
        17: "\"Fleur de l'Éternel\"",
        18: "\"En Ta Présence, Ô Seigneur\"",
        19: "\"Purifiés par Ta Grâce\"",
        20: "\"Dans le Désert, Abreuvez-Nous !\"",
        21: "\"Dans le Désert, notre Force\"",
        22: "\"Dans Ta Lumière, Nous Avançons\"",
        23: "\"Puissance de Bénédiction\"",
        24: "\"Étoile de Jacob, Règne en Nous\"",
        25: "\"Zèle pour la Vérité\"",
        26: "\"Ensemble, Nous Levons Nos Mains\"",
        27: "\"Héritage de Foi\"",
        28: "\"Offrandes de Louange\"",
        29: "\"Fête de Louange au Seigneur\"",
        30: "\"Promesses de Cœur\"",
        31: "\"Victoire et Pureté\"",
        32: "\"Vers la Terre Promise\"",
        33: "\"Stations de Gloire\"",
        34: "\"Les Limites de Sa Promesse\"",
        35: "\"Villes de Refuge\"",
        36: "Héritiers de Sa Promesse",
    },
    "05": {
        1: "\"Avançons avec Foi\"",
        2: "\"Notre Force dans le Désert\"",
        3: "\"Ne Crains Pas, Ô Israël!\"",
        4: "\"Un Peuple Sage\"",
        5: "\"Guidés par Sa Lumière\"",
        6: "\"Écoute, ô Israël!\"",
        7: "\"Choisis et Bénis\"",
        8: "\"N'oublie Pas, Ô Mon Dieu\"",
        9: "\"Promesse et Miséricorde\"",
        10: "\"Héritage de Gloire\"",
        11: "\"Marchons dans Sa Lumière\"",
        12: "\"Dans le Lieu que Tu as Choisi\"",
        13: "\"Marchons dans Ses Voies\"",
        14: "\"Peuple Saint, Loue ton Dieu\"",
        15: "\"Relâche et Bénédiction\"",
        16: "\"Souviens-toi de Ta Libération!\"",
        17: "Lumière de notre Espoir",
        18: "\"Héritage Éternel\"",
        19: "Villes de Refuge, Amour et Vérité",
        20: "\"Avançons en Lui!\"",
        21: "\"Dans Ta Grâce, Eternel\"",
        22: "\"Unis dans l'Amour\"",
        23: "\"Dans Ta Grâce, Seigneur\"",
        24: "\"Unis dans Ta Grâce\"",
        25: "\"Justice et Amour\"",
        26: "\"Prémices de Louange\"",
        27: "\"Ensemble, nous proclamons!\"",
        28: "\"Bénédictions et Louanges\"",
        29: "Alliance d'Amour et de Grâce",
        30: "\"Choisir la Vie\"",
        31: "\"Fortifiez-vous, N'ayez Pas Peur\"",
        32: "\"Rendez Gloire au Rocher\"",
        33: "\"Bénis Sois, Éternel\"",
        34: "\"Promesse au Sommet\"",
    },
    "06": {
        1: "\"Fortifie-toi et Prends Courage\"",
        2: "\"Le Cordon de l'Espoir\"",
        3: "\"Au Bord du Jourdain\"",
        4: "\"Les Pierres du Souvenir\"",
        5: "\"Guilgal, Lieu de Liberté\"",
        6: "\"Les Murs de Jéricho\"",
        7: "\"Restaure-nous, Éternel\"",
        8: "\"Dans Ta Victoire, Éternel\"",
        9: "\"Alliance de Lumière\"",
        10: "\"Le Jour où le Soleil s'est Arrêté\"",
        11: "\"Victoire en Lui\"",
        12: "\"Victoire et Louange\"",
        13: "\"Avancer dans la Promesse\"",
        14: "\"Montagne de Promesse\"",
        15: "\"Héritage de Louange\"",
        16: "\"Notre Héritage, Ta Promesse\"",
        17: "\"Possession et Victoire\"",
        18: "Héritage de Promesse",
        19: "\"Notre Héritage Éternel\"",
        20: "\"Refuge de Grâce\"",
        21: "\"Héritage de Grâce\"",
        22: "\"Unis dans la Louange\"",
        23: "\"Attachés à l'Éternel\"",
        24: "\"Nous Servirons l'Éternel\"",
    },
    "07": {
        1: "\"Dans la Lumière de Ta Victoire\"",
        2: "\"Reviens, ô Éternel\"",
        3: "\"Libérés par Ta Main\"",
        4: "\"Éternel, Lève-Toi !\"",
        5: "\"Éternel, Notre Force et Chant\"",
        6: "\"Notre Force et Notre Paix\"",
        7: "\"Pour l'Éternel et Gédéon\"",
        8: "\"Force et Délivrance\"",
        9: "\"Le Cri Du Sang\"",
        10: "\"Retour à Ta Grâce\"",
        11: "« La Victoire de Jephthé »",
        12: "\"Dans la Victoire de l'Éternel\"",
        13: "\"Promesse de Délivrance\"",
        14: "\"Force et Douceur\"",
        15: "\"Force et Lumière\"",
        16: "\"Force dans la Faiblesse\"",
        17: "\"À Toi, Éternel, notre Roi\"",
        18: "\"Vers la Terre Promise\"",
        19: "\"Dans l'Obscurité, Ta Lumière\"",
        20: "\"Unis dans la Louange\"",
        21: "\"Unis par Ta Grâce\"",
    },
    "08": {
        1: "\"Ton Peuple, Mon Peuple\"",
        2: "Sous les Ailes de Grâce",
        3: "\"À l'ombre de l'amour\"",
        4: "Rédemption à la Porte de Bethléhem",
    },
    "09": {
        1: "1 Samuel 01 — La prière d’Anne, l’appel du cœur",
        2: "\"Roche de Mon Salut\"",
        3: "\"Écoute, Éternel\"",
        4: "\"Éternel, Viens à Notre Secours\"",
        5: "\"Puissance Divine\"",
        6: "\"Rendre Gloire à l'Éternel\"",
        7: "\"Jusqu'ici, Éternel!\"",
        8: "\"Notre Roi Éternel\"",
        9: "\"Guide de mon cœur\"",
        10: "\"Le Roi Oint du Ciel\"",
        11: "\"Notre Secours Éternel\"",
        12: "\"Roi Éternel, notre Sauveur\"",
        13: "\"Guide-nous, Ô Éternel\"",
        14: "\"Confiance en l'Éternel\"",
        15: "\"Obéissance, notre chant de victoire\"",
        16: "\"Un cœur selon ta volonté\"",
        17: "\"Au Nom de l'Éternel\"",
        18: "\"Force et Amitié en Toi\"",
        19: "\"Refuge dans la Tempête\"",
        20: "\"Unis dans la Promesse\"",
        21: "\"Refuge dans la Tempête\"",
        22: "\"Refuge dans la Tempête\"",
        23: "\"Force et Délivrance\"",
        24: "\"Ma Lumière dans l'Ombre\"",
        25: "\"Dans Ta Lumière, Éternel\"",
        26: "\"Ma Lumière dans le Désert\"",
        27: "\"Ma Lumière dans l'Ombre\"",
        28: "\"Dans l'Obscurité, J'Attendrais\"",
        29: "\"Notre Dieu, notre Refuge\"",
        30: "\"Notre Force, Notre Refuge\"",
        31: "\"Dans la Nuit, Ta Lumière\"",
    },
    "10": {
        1: "\"Chant des Héros Tombés\"",
        2: "\"Éternel, Mon Roi\"",
        3: "\"Roi de Promesse\"",
        4: "\"Dans Ta Lumière, Éternel\"",
        5: "\"Roi de Sion, notre Victoire!\"",
        6: "\"Dansons pour l'Éternel!\"",
        7: "\"Éternel, notre Roi\"",
        8: "\"Victorieux par Ta Grâce\"",
        9: "À Ta Table, Seigneur !",
        10: "\"Force et Victoire en Toi\"",
        11: "\"Dans Ta Lumière, Éloigne-moi\"",
        12: "\"Le Cri du Cœur Repenti\"",
        13: "\"Dans la Tempête, Notre Espoir\"",
        14: "\"Restauration et Rédemption\"",
        15: "\"Dans la Vallée des Larmes\"",
        16: "Lumière dans l'Obscurité",
        17: "\"Refuge et Force\"",
        18: "\"Mon Fils, Mon Absalom\"",
        19: "\"Reviens, Ô Roi, Sur Cette Terre\"",
        20: "\"Unis sous notre Roi\"",
        21: "\"Dans l'Espoir de Ta Grâce\"",
        22: "\"Mon Rocher, Ma Victoire\"",
        23: "\"Dans la Lumière du Matin\"",
        24: "\"Dans Ta Grâce, Éternel\"",
    },
    "11": {
        1: "\"Vive le Roi Salomon!\"",
        2: "\"Fortifiés par Ta Promesse\"",
        3: "\"Un Cœur Intelligent\"",
        4: "\"Sous la Vigne de Sagesse\"",
        5: "\"Bâtissons Ensemble pour Ta Gloire\"",
        6: "\"Maison de Gloire\"",
        7: "\"Temple de Gloire\"",
        8: "\"Dans Ta Maison, Éternel\"",
        9: "\"Dans Ta Lumière, Nous Avançons\"",
        10: "\"Le Roi de Sagesse\"",
        11: "\"Ne Laisse Pas Mon Cœur S'égarer\"",
        12: "\"Guide nos Cœurs, Ô Seigneur\"",
        13: "\"À l'écoute de Ta voix\"",
        14: "\"Retour à la Lumière\"",
        15: "\"Une Lampe pour Jérusalem\"",
        16: "\"Vers Ta Lumière, Ô Éternel\"",
        17: "\"Le Pain de Vie\"",
        18: "\"Feu du Ciel, Pluie de Grâce\"",
        19: "\"Dans le Murmure de Ta Présence\"",
        20: "\"Dieu de Bataille, Ma Force\"",
        21: "Héritage de Foi",
        22: "\"Dans la lumière de Ta voix\"",
    },
    "12": {
        1: "\"Seul Toi es notre Direction\"",
        2: "\"Le Manteau de l'Esprit\"",
        3: "\"Des Fosses dans la Vallée\"",
        4: "\"Des Vases Vides, Pleins de Grâce\"",
        5: "\"Le Dieu qui Guérit\"",
        6: "\"Dans le Refuge de l'Éternel\"",
        7: "\"Libération et Joie\"",
        8: "\"Miracles de l'Éternel\"",
        9: "\"Le Roi de la Justice\"",
        10: "\"Libération et Victoire\"",
        11: "\"Joie du Roi, Victoire du Ciel!\"",
        12: "\"Répare en Nous, Ô Éternel\"",
        13: "\"Libération par la Grâce\"",
        14: "\"Éternel, Notre Guide\"",
        15: "\"Fidèle à Jamais\"",
        16: "\"Restaure Nos Cœurs\"",
        17: "\"Reviens à l'Éternel\"",
        18: "\"Ezéchias, notre chant de victoire\"",
        19: "\"Seul, Tu es le Vrai\"",
        20: "\"En Toi, Seigneur, je trouve la vie\"",
        21: "\"Restauration de Jérusalem\"",
        22: "\"Dans la Voie de David\"",
        23: "\"Unis pour l'Éternel\"",
        24: "\"Rappelle-nous, Seigneur\"",
        25: "\"Dans les Cendres, l'Espérance\"",
    },
    "13": {
        1: "\"Des Générations en Louange\"",
        2: "\"Dans Ta Gloire, Nous Marchons\"",
        3: "\"Générations de Gloire\"",
        4: "Élargis mes frontières, ô Dieu d'amour!",
        5: "\"Notre Force, Notre Bouclier\"",
        6: "\"Héritiers de Sa Gloire\"",
        7: "\"Dans Tes Lignées, Seigneur\"",
        8: "\"L'Héritage de Benjamin\"",
        9: "\"Dans ta Maison, Seigneur\"",
        10: "\"Notre Lumière dans l'Ombre\"",
        11: "\"Le Roi de Sion\"",
        12: "\"Unis pour David, Forts en Christ\"",
        13: "\"Ramenons l'Arche de Gloire\"",
        14: "\"Notre Force, Notre Roi\"",
        15: "\"Réjouissance à l'Arche\"",
        16: "\"Chantez à l'Éternel, notre Roi!\"",
        17: "\"Éternel, Bâtisseur de Mon Cœur\"",
        18: "\"Victoire en Ton Nom\"",
        19: "\"Confiance en Toi, Ô Seigneur\"",
        20: "\"Victorious dans la foi\"",
        21: "\"Au Cœur de Ta Miséricorde\"",
        22: "\"Construire pour l'Éternel\"",
        23: "\"Repose en Ta Présence\"",
        24: "\"Serviteurs de Gloire\"",
        25: "\"Unis pour Louer\"",
        26: "\"Portiers de Ta Gloire\"",
        27: "\"Ensemble pour Sa Gloire\"",
        28: "\"Fortifiés dans Ta Maison\"",
        29: "\"À Toi, l'Éternel, notre Louange\"",
    },
    "14": {
        1: "\"Sagesse et Gloire\"",
        2: "\"Nous Bâtissons pour Ta Gloire\"",
        3: "\"Maison de Gloire\"",
        4: "\"Dans Ta Maison, Seigneur\"",
        5: "\"Dans Ta Gloire, Éternel\"",
        6: "\"Éternel, notre Salvation\"",
        7: "\"Dans la Gloire du Seigneur\"",
        8: "\"Maison de Gloire\"",
        9: "\"Salomon, Roi de Sagesse\"",
        10: "\"Écoute, Ô Roi!\"",
        11: "\"Écoute Sa Voix, Ô Roi\"",
        12: "\"Reviens à Ta Grâce\"",
        13: "\"Notre Dieu, notre Victoire\"",
        14: "\"Notre Force, Ô Eternel\"",
        15: "\"Cherchons l'Éternel de Tout notre Cœur!\"",
        16: "\"Refuge de l'Éternel\"",
        17: "\"Dans les Voies de Josaphat\"",
        18: "\"Dans la bataille, notre Roi\"",
        19: "\"Dans la Crainte de l'Éternel\"",
        20: "\"Notre Force, notre Chant\"",
        21: "\"Ne Laisse Pas notre Cœur Errer\"",
        22: "\"Règne, Seigneur, fais-nous croire\"",
        23: "\"Vive le Roi, notre Sauveur\"",
        24: "\"Restauration des Cœurs\"",
        25: "\"Dans Ta Lumière, Nous Avancerons\"",
        26: "\"Dans l'Honneur et l'Humilité\"",
        27: "\"Jotham, Roi de Foi\"",
        28: "\"Reviens à l'Éternel\"",
        29: "\"Restauration de Louange\"",
        30: "\"Revenons à l'Éternel\"",
        31: "\"Le Cœur de Louange\"",
        32: "\"Notre Bouclier, notre Victoire\"",
        33: "\"Dans Ta Grâce, Seigneur\"",
        34: "\"Josias, Roi de Louange\"",
        35: "\"Liberté de la Pâque\"",
        36: "\"Le cri du cœur vers l'Éternel\"",
    },
    "15": {
        1: "\"Vers Jérusalem, nous te bâtirons\"",
        2: "\"Retour à la Maison\"",
        3: "\"Unis dans la Louange\"",
        4: "\"Nous Bâtissons pour Ta Gloire\"",
        5: "\"Rebâtissons pour Ta Gloire\"",
        6: "\"Renaissance de Ta Maison\"",
        7: "\"Esdras, Héraut de l'Éternel\"",
        8: "\"Main de notre Dieu\"",
        9: "\"Restauration de notre cœur\"",
        10: "\"Alliance de Cœurs\"",
    },
    "16": {
        1: "\"Rassemble Ton Peuple, Ô Éternel\"",
        2: "\"Rebâtissons avec Foi\"",
        3: "\"Bâtisseurs de Gloire\"",
        4: "\"Rebâtissons avec Foi\"",
        5: "\"Unis dans la Louange\"",
        6: "\"Fortifié par Ta Main\"",
        7: "\"Rassemble ton Peuple\"",
        8: "\"Joie de l'Éternel, notre force\"",
        9: "\"Fidèle Éternel, notre Roi\"",
        10: "\"Unis dans Ta Promesse\"",
        11: "\"À Jérusalem, notre louange!\"",
        12: "\"Réjouissons-nous, Jérusalem!\"",
        13: "\"Souviens-Toi de Nous, Seigneur\"",
    },
    "17": {
        1: "\"Dans Ta Grandeur, Seigneur\"",
        2: "\"Esther, Lumière de Courage\"",
        3: "\"Debout dans la Foi\"",
        4: "\"Pour un Temps Comme Celui-ci\"",
        5: "\"Grâce dans la Cour du Roi\"",
        6: "\"Le Roi des Rois Honore\"",
        7: "\"Dans la lumière de la justice\"",
        8: "\"Libération et Joie\"",
        9: "\"Victorieusement Libérés\"",
        10: "\"Pour le Bien de Son Peuple\"",
    },
    "18": {
        1: "\"Que Ton Nom Soit Béni\"",
        2: "\"Fidèle au Milieu de la Tempête\"",
        3: "\"Dans l'Obscurité, J'Appelle à Toi\"",
        4: "\"Refuge dans la Tempête\"",
        5: "\"Espérance en Lui\"",
        6: "\"Dans l'Abîme, J'Appelle à Toi\"",
        7: "\"Souffle de Vie\"",
        8: "\"Chants de Joie et de Foi\"",
        9: "\"Dans Ta Grandeur, je Loue\"",
        10: "\"Ne Me Condamne Pas, Ô Créateur\"",
        11: "\"Vers Ta Lumière\"",
        12: "\"Sagesse Éternelle\"",
        13: "\"Dans Ta Lumière, Seigneur\"",
        14: "\"Espérance dans les Larmes\"",
        15: "\"Dans Ta Vérité, Seigneur\"",
        16: "\"Mon Témoin dans les Cieux\"",
        17: "\"Ma Force Parfaite\"",
        18: "Lumière dans l'Obscurité",
        19: "\"Mon Rédempteur est Vivant\"",
        20: "\"Le Sort des Impies\"",
        21: "\"Dans l'Épreuve, Ma Louange\"",
        22: "\"Attache-toi à Dieu\"",
        23: "\"À la recherche de Ta lumière\"",
        24: "\"Justice et Espoir\"",
        25: "\"Dans Ta Lumière, Ô Éternel\"",
        26: "\"Puissance et Sagesse\"",
        27: "\"Je Tiens Ferme en Toi\"",
        28: "\"Dans Ta Sagesse, Seigneur\"",
        29: "\"Refuge de Mon Cœur\"",
        30: "\"Dans la Nuit, J'Implore\"",
        31: "\"Mon Pacte avec Toi\"",
        32: "\"Écoute, Ô Dieu\"",
        33: "\"Écoute et Lève-toi\"",
        34: "\"Éternel, notre Juste Roi\"",
        35: "\"Regarde les Cieux\"",
        36: "\"Élevé par Sa Grâce\"",
        37: "\"Majesté du Créateur\"",
        38: "\"Dans la Tempête, Ta Voix\"",
        39: "\"Dans la Sagesse du Créateur\"",
        40: "\"Majesté du Tout-Puissant\"",
        41: "\"Majesté des Profondeurs\"",
        42: "\"Restauration dans Ta Grâce\"",
    },
    "19": {
        1: "\"Racines dans l'Éternel\"",
        2: "\"Le Roi Établi\"",
        3: "\"Mon Bouclier, Ma Foi\"",
        4: "\"Lumière de Mon Cœur\"",
        5: "\"Dans ta Grâce, je me Confie\"",
        6: "\"Dans Ta Miséricorde\"",
        7: "\"Justice et Louange au Très-Haut\"",
        8: "\"Magnifique Éternel!\"",
        9: "\"Règne, Ô Éternel!\"",
        10: "\"Seigneur, Lève-Toi !\"",
        11: "\"Refuge Éternel\"",
        12: "\"Dans l'ombre des faussetés\"",
        13: "\"Dans Ta Lumière, Seigneur\"",
        14: "\"Éveille nos cœurs, Seigneur\"",
        15: "\"Sur Ta Montagne, Éternel\"",
        16: "\"Mon Héritage Éternel\"",
        17: "\"À l'Ombre de Tes Ailes\"",
        18: "\"Mon Rocher, ma Délivrance\"",
        19: "\"Chant des Cieux et de la Loi\"",
        20: "\"Dans la Détresse, Tu es Là\"",
        21: "\"Dans Ta Puissance, Éternel\"",
        22: "\"Mon Dieu, Mon Espoir\"",
        23: "\"Mon Berger, Mon Réconfort\"",
        24: "\"Le Roi de Gloire\"",
        25: "\"Mon Espoir Éternel\"",
        26: "\"Dans Ta Vérité, Seigneur\"",
        27: "\"Espère en l'Éternel\"",
        28: "\"Mon Rocher, Ma Force\"",
        29: "\"Résonne, Ô Voix de l'Éternel!\"",
        30: "\"Allégresse au Matin\"",
        31: "\"Refuge de Mon Âme\"",
        32: "\"Chants de Délivrance\"",
        33: "\"Notre Espoir, Ô Éternel!\"",
        34: "\"Rayonnons de Joie\"",
        35: "\"Défenseur de mon âme\"",
        36: "\"Dans l'Abondance de Ta Maison\"",
        37: "\"Espérance en l'Éternel\"",
        38: "\"Viens à Mon Secours\"",
        39: "\"Dans l'Espoir de l'Éternel\"",
        40: "\"Cantique Nouveau pour l'Éternel\"",
        41: "\"Dans Tes Bras, Seigneur\"",
        42: "\"Espère en Dieu, Mon Âme\"",
        43: "\"Lumière de Mon Sauveur\"",
        44: "\"Réveille-toi, Seigneur!\"",
        45: "\"Roi de Gloire, Épée de Vérité\"",
        46: "\"Refuge Éternel\"",
        47: "\"Le Roi des Nations\"",
        48: "\"Notre Dieu Éternel\"",
        49: "\"Notre Refuge Éternel\"",
        50: "\"Rassemble tes Fidèles\"",
        51: "\"Un Cœur Pur\"",
        52: "\"Confiance Éternelle\"",
        53: "\"Vers Ta Lumière, Seigneur\"",
        54: "\"Mon Secours Éternel\"",
        55: "\"Dans Tes Bras, Ô Mon Sauveur\"",
        56: "\"En Toi, je me Confie\"",
        57: "\"À l'Ombre de Tes Ailes\"",
        58: "\"Justice et Louange\"",
        59: "\"Ma Haute Retraite\"",
        60: "\"Élève Ta Bannière, Seigneur!\"",
        61: "\"Mon Refuge Éternel\"",
        62: "\"Confiance en Mon Rocher\"",
        63: "\"À l'ombre de tes ailes\"",
        64: "\"Mon Refuge, Ma Victoire\"",
        65: "\"Dans le Bonheur de Ta Maison\"",
        66: "\"Chantons sa Gloire!\"",
        67: "\"Tous les Peuples Te Louent\"",
        68: "\"Réjouissez-vous, le Seigneur est là!\"",
        69: "\"Dans la Tempête, J'Embrasse Ta Grâce\"",
        70: "\"Hâte-toi, Ô Dieu!\"",
        71: "\"Mon Refuge Éternel\"",
        72: "\"Règne de Justice et de Paix\"",
        73: "\"Ma Lumière, Mon Refuge\"",
        74: "\"Défends Ta Cause, Ô Dieu!\"",
        75: "\"Élevés par Ta Grâce\"",
        76: "\"Majesté de notre Dieu\"",
        77: "\"Souviens-toi de Tes Merveilles\"",
        78: "\"Notre Rocher, Notre Espérance\"",
        79: "\"À Toi, notre Espoir\"",
        80: "\"Relève-nous, Ô Éternel!\"",
        81: "\"Ouvre Ta Bouche\"",
        82: "\"Justice et Lumière\"",
        83: "\"Montre Ta Force, Ô Éternel!\"",
        84: "\"Dans Ta Maison, Éternel\"",
        85: "\"Rétablis-nous, Ô Éternel!\"",
        86: "\"Éternel, Entends Ma Prière\"",
        87: "\"Sources de Sion\"",
        88: "\"Mon Cri vers Toi\"",
        89: "\"Fidèle à Jamais\"",
        90: "\"Refuge Éternel\"",
        91: "\"Mon Refuge, Mon Eternel\"",
        92: "\"Dans la Gloire de l'Eternel\"",
        93: "Majesté Éternelle",
        94: "\"Éternel, notre Refuge\"",
        95: "\"Chantons au Rocher de notre Salut\"",
        96: "\"Chantez à l'Éternel\"",
        97: "\"Règne de Gloire\"",
        98: "\"Chantez à l'Éternel, le Roi des cieux!\"",
        99: "\"Règne de Sainteté\"",
        100: "\"Dans la Joie de l'Éternel\"",
        101: "\"Dans Ta Lumière, Éternel\"",
        102: "\"Mon Refuge Éternel\"",
        103: "Bénis l'Éternel, mon âme!",
        104: "\"Bénis l'Éternel, mon âme!\"",
        105: "\"Souviens-toi de l'Éternel!\"",
        106: "\"Souviens-Toi de Nous, Éternel!\"",
        107: "\"Chantons Sa Bonté Éternelle\"",
        108: "\"Élève-toi, Ô Dieu!\"",
        109: "\"Agis pour Moi, Ô Seigneur\"",
        110: "\"Le Sceptre de la Gloire\"",
        111: "\"À Jamais, Louange à l'Éternel\"",
        112: "\"Heureux l'Homme de Foi\"",
        113: "\"Élevons Nos Voix au Très-Haut\"",
        114: "\"Le Dieu de notre délivrance\"",
        115: "\"À Ton Nom, Seigneur\"",
        116: "\"Dans Tes Bras, Ô Éternel\"",
        117: "\"Chantons à l'Éternel, notre Fidèle!\"",
        118: "\"Sa Miséricorde Dure À Jamais\"",
        119: "\"Dans la Lumière de Ta Loi\"",
        120: "\"Ma Paix dans la Tempête\"",
        121: "\"Mon Gardien Éternel\"",
        122: "\"À la Maison de l'Éternel\"",
        123: "\"À Toi, Éternel, nos Yeux Se Tournent\"",
        124: "\"Notre Secours Éternel\"",
        125: "\"En Toi, Ma Montagne\"",
        126: "\"Des Larmes aux Chants d'Allégresse\"",
        127: "\"Dans Ta Main, Seigneur\"",
        128: "\"Heureux L'Homme de Dieu\"",
        129: "\"Libérés par Sa Justice\"",
        130: "\"Espoir du Matin\"",
        131: "\"Espoir Éternel\"",
        132: "\"Éternel, Lève-toi pour Ta Demeure\"",
        133: "\"Unis dans Ta Grâce\"",
        134: "\"Dans Ta Maison, Seigneur\"",
        135: "\"Louons l'Éternel, notre Sauveur!\"",
        136: "\"Sa Miséricorde Dure à Jamais\"",
        137: "Souviens-toi de Sion",
        138: "\"Éternelle Bonté, Mon Chant\"",
        139: "\"Dans Ta Lumière, Éternel\"",
        140: "\"Mon Refuge, Mon Éternel\"",
        141: "\"Mon Refuge Éternel\"",
        142: "\"Mon Refuge, Ma Lumière\"",
        143: "\"Mon âme soupire après Toi\"",
        144: "\"Mon Rocher, Mon Salut\"",
        145: "\"À Jamais, je Te Louerai\"",
        146: "\"À Jamais Louez l'Éternel!\"",
        147: "\"Rebâtis, Ô Éternel\"",
        148: "\"Louons l'Éternel, Créateur Éternel\"",
        149: "\"Chantons à l'Éternel\"",
        150: "\"Chant de Louange Éternelle\"",
    },
    "20": {
        1: "\"Écoute la Sagesse\"",
        2: "\"Voies de Sagesse\"",
        3: "\"Confie-toi en l'Éternel\"",
        4: "\"Sur le Chemin de la Sagesse\"",
        5: "\"Reste dans la Lumière\"",
        6: "Éveille-toi et avance !",
        7: "\"Écoute la Sagesse\"",
        8: "\"Voix de Sagesse\"",
        9: "\"Sagesse, Éclaire Nos Cœurs\"",
        10: "\"Le Chant des Justes\"",
        11: "\"Justice et Vérité\"",
        12: "\"Établis-nous dans Ta lumière\"",
        13: "\"Dans Ta Lumière, Nous Marchons\"",
        14: "\"Sagesse et Réfuge\"",
        15: "\"Réponse de Paix\"",
        16: "\"Chemin Doré\"",
        17: "\"Paix et Sagesse en Toi\"",
        18: "\"Ma Tour Forte\"",
        19: "\"Guide mes Pas, Ô Éternel\"",
        20: "\"Éveille Nos Cœurs\"",
        21: "\"Dans Ta Main, Éternel\"",
        22: "\"Richesse de Grâce\"",
        23: "\"Éveille en Moi la Sagesse\"",
        24: "\"Élève Ma Maison\"",
        25: "\"Dans Ta Gloire, Ô Roi\"",
        26: "\"Sagesse et Gloire\"",
        27: "\"Dans Ta Lumière, Je Marche\"",
        28: "\"Force et Lumière\"",
        29: "\"Justice et Joie en Toi\"",
        30: "\"Refuge de Vérité\"",
        31: "\"Femme de Force et de Foi\"",
    },
    "21": {
        1: "\"Vanité des Vanités, Mon Espoir\"",
        2: "\"Mon Héritage Éternel\"",
        3: "\"Tout a son Temps\"",
        4: "\"Ensemble dans la Lumière\"",
        5: "\"Dans Ta Présence, Seigneur\"",
        6: "\"Le Vrai Bonheur\"",
        7: "\"Dans la Maison de Deuil\"",
        8: "\"Dans Ta Lumière, Seigneur\"",
        9: "\"Espoir sous le Ciel\"",
        10: "\"Guide Nos Pas, Ô Seigneur\"",
        11: "\"Jette ton Pain sur les Eaux\"",
        12: "\"Souviens-toi de ton Créateur\"",
    },
    "22": {
        1: "\"Entraîne-moi, Mon Bien-Aimé\"",
        2: "\"Amour Éternel\"",
        3: "\"À la Recherche de l'Amour\"",
        4: "\"Dans le Jardin de Mon Amie\"",
        5: "\"Enivrés d'Amour\"",
        6: "\"Dans le Jardin de Ton Amour\"",
        7: "\"Beauté Éternelle\"",
        8: "\"L'Amour Éternel\"",
    },
    "23": {
        1: "\"Reviens à Ta Grâce\"",
        2: "\"Montons à la Maison de l'Éternel\"",
        3: "\"Refuge dans la Tempête\"",
        4: "\"Refuge de Gloire\"",
        5: "\"Chant de la Vigne Éternelle\"",
        6: "\"Saint, Saint, Saint est l'Éternel!\"",
        7: "\"Emmanuel, notre espoir\"",
        8: "\"Emmanuel, notre force\"",
        9: "Lumière dans les Ténèbres",
        10: "\"Notre Refuge, notre Force\"",
        11: "\"Rameau de Gloire\"",
        12: "\"Sources de Salut\"",
        13: "\"Le Jour de l'Éternel\"",
        14: "\"Renaître en Sion\"",
        15: "\"Dans la Lamentation, Brille l'Espoir\"",
        16: "\"Refuge de Justice\"",
        17: "\"Regarde vers Ton Créateur\"",
        18: "\"Élevez Vos Yeux\"",
        19: "\"Sur les Nuées de l'Espoir\"",
        20: "\"Notre Refuge, Notre Espoir\"",
        21: "\"Dans la Tempête, Seigneur, Nous Te Louons!\"",
        22: "\"Clé de la Promesse\"",
        23: "\"Le Cri des Mers\"",
        24: "\"Renaître dans Sa Gloire\"",
        25: "\"Notre Refuge, Notre Roi\"",
        26: "\"Paix Éternelle, Roc de notre Foi\"",
        27: "\"Vigne de Victoire\"",
        28: "\"Pierre Angulaire de Notre Foi\"",
        29: "\"Éternel, notre lumière\"",
        30: "\"Notre Libérateur\"",
        31: "\"Rugissement du Lion\"",
        32: "\"Roi de Justice, Source de Paix\"",
        33: "\"À Toi, Éternel, notre Refuge\"",
        34: "\"Justice et Gloire de l'Éternel\"",
        35: "\"Voie Sainte, Joie Éternelle\"",
        36: "\"Notre Refuge Éternel\"",
        37: "\"Éternel, notre Sauveur\"",
        38: "\"Rétabli par Ta Grâce\"",
        39: "\"Lumière dans la Tempête\"",
        40: "\"Voici Votre Dieu\"",
        41: "\"Ne Crains Rien, Je Te Fortifie\"",
        42: "\"Chantez à l'Éternel !\"",
        43: "\"À Moi, Bien-Aimé\"",
        44: "\"Racheté par l’Éternel\"",
        45: "\"Il N'y a Point d'Autre Dieu\"",
        46: "\"Notre Refuge Éternel\"",
        47: "\"Le Temps de la Rédemption\"",
        48: "\"Racheté par l'Éternel\"",
        49: "\"Lumière des Nations\"",
        50: "\"Ma Lumière dans l'Obscurité\"",
        51: "\"Réveille-toi, Sion!\"",
        52: "Réveille-toi, Sion!",
        53: "\"Jésus, notre Sauveur Brisé\"",
        54: "\"Réjouis-toi, ô Stérile!\"",
        55: "\"Venez aux Eaux de Vie\"",
        56: "\"Un Nom Éternel\"",
        57: "\"Paix pour les Cœurs Contrits\"",
        58: "\"Libérés pour Aimer\"",
        59: "\"Rappelle-Nous à Tes Cieux\"",
        60: "\"Lumière de Sion\"",
        61: "\"Année de Grâce\"",
        62: "\"Jérusalem, Joyau de l'Éternel\"",
        63: "\"Le Cri de notre Rédempteur\"",
        64: "\"Viens, Seigneur, fais-nous voir ta gloire !\"",
        65: "\"Réjouis-toi, Jérusalem!\"",
        66: "\"Dans Tes Bras, Éternel\"",
    },
    "24": {
        1: "\"Je suis avec toi\"",
        2: "\"Reviens à Ta Source\"",
        3: "\"Reviens à Ton Père\"",
        4: "\"Reviens à Ton Seigneur\"",
        5: "\"Ramène-nous, Oh Éternel\"",
        6: "\"Vers la Voie de la Grâce\"",
        7: "\"Réveille nos cœurs, Éternel\"",
        8: "\"Dans Ta Lumière, Seigneur\"",
        9: "\"Larmes de Vérité\"",
        10: "\"Seigneur, Nul n'est Comme Toi\"",
        11: "\"Écoute, Ô Peuple Bien-Aimé\"",
        12: "\"Restaure, Éternel\"",
        13: "\"Reviens vers la lumière\"",
        14: "\"Restaure-nous, Ô Éternel\"",
        15: "\"Rappelle-toi, Éternel\"",
        16: "\"Éternel, Notre Refuge\"",
        17: "\"Fleurir près des Eaux\"",
        18: "\"Entre Tes Mains, Seigneur\"",
        19: "\"Vase Brisé, Cœur Ramené\"",
        20: "\"Mon Héros Éternel\"",
        21: "\"Chemin de Vie, Lumière Éternelle\"",
        22: "\"Voix de l'Éternel\"",
        23: "\"Rassemble-nous, Éternel\"",
        24: "\"Les Figues de l’Espérance\"",
        25: "\"Reviens à Moi, ô Juda!\"",
        26: "\"Reviens vers l'Éternel\"",
        27: "Sous le Joug de Ta Grâce",
        28: "\"Le Joug Brisé\"",
        29: "\"Espoir au Coeur de l'Exil\"",
        30: "\"Le Jour de la Délivrance\"",
        31: "\"Rassemble Ton Peuple, Ô Éternel!\"",
        32: "\"Force et Promesse\"",
        33: "\"Appel à la Rédemption\"",
        34: "\"Liberté Éternelle\"",
        35: "\"Fidèles sous Ta Tente\"",
        36: "\"Écoute notre Cri, Éternel\"",
        37: "\"Dans la lumière de Ta promesse\"",
        38: "\"Voix de Vie dans la Tempête\"",
        39: "\"Notre Refuge Éternel\"",
        40: "\"Liberté dans les Chaînes\"",
        41: "\"Dans l'ombre, notre lumière\"",
        42: "\"Dans Ta Voix, Nous Trouvons la Paix\"",
        43: "\"Écoute, Ô Mon Peuple!\"",
        44: "\"Rassemble-nous, Éternel\"",
        45: "\"Force dans l'Épreuve\"",
        46: "\"Force et Salut\"",
        47: "\"Torrent de Grâce\"",
        48: "\"Au Cœur de la Tempête\"",
        49: "\"Dans les Ruines, Nous Te Louons\"",
        50: "\"Vers Sion, Mon Espoir\"",
        51: "\"Vent de Justice\"",
        52: "\"Dans la Tempête, Ta Grâce\"",
    },
    "25": {
        1: "\"Regarde Notre Souffrance\"",
        2: "\"Restaure, Seigneur, notre Sion\"",
        3: "\"Fidélité au Milieu de la Tempête\"",
        4: "\"Restauration de Sion\"",
        5: "\"Souviens-Toi, Éternel!\"",
    },
    "26": {
        1: "\"Vision de Gloire\"",
        2: "\"Fils de l'Homme, Lève-toi!\"",
        3: "\"Écoute et Parle\"",
        4: "\"Dans l'Épreuve, Nous Sommes Ensemble\"",
        5: "\"Restauration de Jérusalem\"",
        6: "\"Écoute, Ô Montagnes d'Israël\"",
        7: "\"Rappelle-nous à Toi, Éternel\"",
        8: "\"Regarde, ô fils de l'homme\"",
        9: "\"Marque de Pardon\"",
        10: "\"Au Seuil de Ta Gloire\"",
        11: "\"Rassemble-nous, Ô Éternel\"",
        12: "\"Promesse Accomplie\"",
        13: "\"Dans Ta Vérité, Seigneur\"",
        14: "\"Reviens à Ta Grâce\"",
        15: "\"Restaure en Nous Ta Douce Face\"",
        16: "\"Rédemption de Jérusalem\"",
        17: "\"Élevé par Ta Main\"",
        18: "\"Reviens et Vis\"",
        19: "\"Rugissements de Rédemption\"",
        20: "\"Reviens à l'Éternel\"",
        21: "\"L'Épée de Justice\"",
        22: "\"Restaure Nos Âmes\"",
        23: "\"Ramène-nous à Toi\"",
        24: "\"Malheur et Miséricorde\"",
        25: "\"Tu es l'Éternel, notre Roi\"",
        26: "\"Le Rocher des Nations\"",
        27: "\"Chute de Tyr, Lamentation des Nations\"",
        28: "\"Éternel, notre Roi\"",
        29: "\"Éternel, Souverain des Nations\"",
        30: "\"Dans la Tempête, Tu Es Mon Refuge\"",
        31: "\"À Qui Ressembles-Tu?\"",
        32: "\"Le Juge des Nations\"",
        33: "\"Retour à la Grâce\"",
        34: "\"Rassemblement des Égarés\"",
        35: "\"Justice des Montagnes\"",
        36: "\"Renaître sur les Montagnes\"",
        37: "\"Revivez, Ô Peuple Bien-Aimé\"",
        38: "\"Éternel, notre Espoir\"",
        39: "\"Notre Vainqueur, L'Éternel\"",
        40: "\"Dans Ta Maison, Éternel\"",
        41: "\"Dans Ta Maison, Seigneur\"",
        42: "\"Dans la Maison du Saint\"",
        43: "\"Dans Ta Maison, Éternel\"",
        44: "\"Sanctuaire de Gloire\"",
        45: "\"Portion Sainte, Cœur Unifié\"",
        46: "\"À la Porte de la Louange\"",
        47: "\"Source de Vie Éternelle\"",
        48: "L'Éternel est ici !",
    },
    "27": {
        1: "\"Aux Cœurs Courageux\"",
        2: "\"Pierre de Sagesse\"",
        3: "\"Au Milieu du Feu\"",
        4: "\"Le Souverain Éternel\"",
        5: "\"Le Roi des Cieux, notre Louange\"",
        6: "\"Dans la fosse des lions, je loue!\"",
        7: "\"Règne Éternel, Gloire Suprême\"",
        8: "\"Règne de Vérité\"",
        9: "\"Seigneur, Entends Notre Prière!\"",
        10: "\"Daniel, Homme Bien-Aimé\"",
        11: "\"Dans la Tempête, Tu es Souverain\"",
        12: "\"Briller pour l'Éternité\"",
    },
    "28": {
        1: "\"Le Coeur de l'Éternel\"",
        2: "\"Reviens à l'Amour\"",
        3: "\"Rends-toi à l'Éternel\"",
        4: "\"Restaure nos Cœurs, Seigneur!\"",
        5: "\"Réveille nos âmes, Seigneur\"",
        6: "\"Retour à l'Éternel\"",
        7: "\"Reviens, Ô Israël\"",
        8: "\"Rassemble Ton Peuple, Seigneur\"",
        9: "\"Reviens à l'Éternel\"",
        10: "\"Rappelle-nous, Ô Éternel\"",
        11: "\"Appel à la Rédemption\"",
        12: "Reviens à Ton Dieu",
        13: "\"Seul Dieu, notre Sauveur\"",
        14: "\"Reviens à Ton Dieu\"",
    },
    "29": {
        1: "\"Restaure notre Terre\"",
        2: "\"Revenons à Toi, Éternel!\"",
        3: "\"Retour à Sion, notre Refuge\"",
    },
    "30": {
        1: "\"Le Rugissement de l'Éternel\"",
        2: "\"Rappelle-nous, Éternel\"",
        3: "\"Écoute, O Israël!\"",
        4: "\"Revenez à l'Éternel\"",
        5: "\"À la Lumière de l'Éternel\"",
        6: "\"Réveillez-vous, Peuple Bien-Aimé\"",
        7: "\"Seigneur, notre Refuge\"",
        8: "\"Corbeille de Fruits : Retour à l'Éternel\"",
        9: "\"Relève-moi, Ô Éternel!\"",
    },
    "31": {
        1: "\"Le Jour de l'Éternel\"",
    },
    "32": {
        1: "\"Dans la Tempête, Ta Grâce\"",
        2: "\"Dans les Profondeurs, je Te Loue\"",
        3: "\"Retour à la Grâce\"",
        4: "\"Miséricorde Éternelle\"",
    },
    "33": {
        1: "\"Quand le Cœur Pleure, Éternel se Lève\"",
        2: "\"Rassemble-nous, Éternel!\"",
        3: "\"Rends-nous la Justice, Éternel\"",
        4: "\"Vers la Montagne d'Amour\"",
        5: "\"Roi de la Paix, Éternel\"",
        6: "\"Marchons avec notre Dieu\"",
        7: "\"Regarde vers l'Éternel\"",
    },
    "34": {
        1: "\"Le Refuge Éternel\"",
        2: "\"Victorious en Ton Nom\"",
        3: "\"Ninive, où es-tu ?\"",
    },
    "35": {
        1: "\"Mon Rocher, Ma Sécurité\"",
        2: "\"Dans la Foi, Nous Trouvons la Joie\"",
        3: "\"Dans Ta Gloire, Éternel\"",
    },
    "36": {
        1: "\"Le Jour de l'Éternel\"",
        2: "\"Refuge dans la Tempête\"",
        3: "\"Réveille-toi, ô Sion!\"",
    },
    "37": {
        1: "\"Réveille Nos Âmes, Seigneur\"",
        2: "\"Fortifiés par Sa Gloire\"",
    },
    "38": {
        1: "\"Reviens à Moi, Ô Jérusalem\"",
        2: "\"Jérusalem, Éveille-toi!\"",
        3: "\"Revêtu de Grâce\"",
        4: "\"Par Ton Esprit, Ô Éternel\"",
        5: "\"Rouleau de Justice\"",
        6: "\"Les Chars de Gloire\"",
        7: "\"Rends-nous la Justice\"",
        8: "\"Fortifie Nos Mains, Ô Seigneur\"",
        9: "\"Le Roi de Paix\"",
        10: "\"Rassemble-nous, Éternel!\"",
        11: "\"Le Berger de Grâce\"",
        12: "\"Jérusalem, notre lumière\"",
        13: "\"Source de Purification\"",
        14: "\"Le Jour de l'Éternel\"",
    },
    "39": {
        1: "\"Grand est l'Éternel\"",
        2: "\"Ramenons Nos Cœurs\"",
        3: "\"Viens, Seigneur de Lumière\"",
        4: "\"Le Jour de la Justice\"",
    },
    "40": {
        1: "\"Emmanuel, Dieu avec nous\"",
        2: "\"À Tes Pieds, Roi des Rois\"",
        3: "\"Préparez le Chemin du Seigneur\"",
        4: "\"Ma Lumière dans le Désert\"",
        5: "\"Heureux dans la Lumière\"",
        6: "\"Dans le Secret de Ta Présence\"",
        7: "\"Sur le Roc de Ta Vérité\"",
        8: "\"Jésus, notre Espoir, notre Guérisseur\"",
        9: "\"Seigneur de Miséricorde\"",
        10: "\"Sur les chemins de l'espérance\"",
        11: "\"Venez à Moi, Trouvez le Repos\"",
        12: "\"Maître du Sabbat, Lumière de nos Vies\"",
        13: "\"Semences de Gloire\"",
        14: "\"Marche sur les Flots\"",
        15: "\"Seigneur, Ouvre Nos Yeux\"",
        16: "\"Ô notre Lumière\"",
        17: "\"Brille, Lumière du Monde\"",
        18: "\"Enfants du Royaume\"",
        19: "\"Unis dans ta Grâce\"",
        20: "\"Les Derniers Seront Premiers\"",
        21: "\"Hosanna au Roi\"",
        22: "\"Venez aux Noces du Roi\"",
        23: "\"Élève-nous, Seigneur\"",
        24: "\"Viens, Seigneur, dans Ta Gloire\"",
        25: "Veillons à la Lumière !",
        26: "\"Le Sacrifice de l'Amour\"",
        27: "\"Le Roi Crucifié, Notre Espoir\"",
        28: "\"Ressuscité, notre Espoir\"",
    },
    "41": {
        1: "\"Préparez le Chemin\"",
        2: "\"Levez-vous et marchez !\"",
        3: "\"Libérés par Ta Main\"",
        4: "\"Semeurs de Vie\"",
        5: "\"Libéré par Ta Grâce\"",
        6: "\"Notre Berger, Notre Lumière\"",
        7: "\"Du Cœur à la Louange\"",
        8: "\"Rassasie nos âmes\"",
        9: "\"Sur la Montagne de Gloire\"",
        10: "\"Unis dans Ta Grâce\"",
        11: "Hosanna au Roi des Rois",
        12: "\"Pierre de Lumière\"",
        13: "\"Veillez et Priez\"",
        14: "\"Dans l'Ombre de Gethsémané\"",
        15: "« Le Roi Crucifié »",
        16: "\"Alléluia, Il Est Vivant !\"",
    },
    "42": {
        1: "\"Promesse de Lumière\"",
        2: "\"Naissance d'une Lumière\"",
        3: "\"Préparez le chemin du Seigneur\"",
        4: "\"Libérateur de Nos Cœurs\"",
        5: "\"À Genoux devant le Maître\"",
        6: "\"Maître du Sabbat\"",
        7: "\"Guérisseur de nos cœurs\"",
        8: "\"Semences de Vie\"",
        9: "\"Suivons le Roi\"",
        10: "\"Envoyés pour la Moisson\"",
        11: "\"Dans la Lumière de la Prière\"",
        12: "\"Veillons dans la Lumière\"",
        13: "\"Repentance et Lumière\"",
        14: "\"Élevés par Ta Grâce\"",
        15: "\"Retrouvé dans la Grâce\"",
        16: "\"Les Vraies Richesses\"",
        17: "\"Augmente en Nous la Foi\"",
        18: "\"Justice et Humilité\"",
        19: "\"Béni soit le Roi qui nous sauve !\"",
        20: "\"Pierre Angulaire\"",
        21: "\"Notre Refuge, Notre Espoir\"",
        22: "\"Dans la Nuit de la Pâque\"",
        23: "\"Libérés par la Croix\"",
        24: "\"Il est Vivant, Alléluia !\"",
    },
    "43": {
        1: "\"Lumière du Monde\"",
        2: "\"Le Meilleur Vin\"",
        3: "\"Né de Nouveau\"",
        4: "\"Source de Vie\"",
        5: "\"Lève-toi et marche\"",
        6: "\"Pain de Vie, Lumière du Monde\"",
        7: "\"Venez à Moi, Source de Vie\"",
        8: "Lumière du Monde, Liberté en Jésus",
        9: "Lumière de Vie",
        10: "\"Le Bon Berger\"",
        11: "\"Résurrection et Vie\"",
        12: "\"Hosanna, notre Roi\"",
        13: "\"À Tes Pieds, Seigneur\"",
        14: "\"Je Ne Te Laisserai Pas\"",
        15: "\"Racines d'Amour\"",
        16: "\"Joie au Milieu des Larmes\"",
        17: "\"Unis dans Ta Gloire\"",
        18: "\"Le Roi des Cieux\"",
        19: "\"Couronne d'Épines, Amour Éternel\"",
        20: "“Ressuscité, notre Espoir”",
        21: "\"Sur les Rives de Sa Grâce\"",
    },
    "44": {
        1: "\"Dans l'Attente de l'Esprit\"",
        2: "\"Saint-Esprit, Lumière de nos âmes\"",
        3: "\"Levez-vous et Marchez !\"",
        4: "\"Pierre Angulaire de notre Foi\"",
        5: "\"Dans l'ombre de Ta gloire\"",
        6: "\"Unis dans la Grâce\"",
        7: "\"Refuge de Gloire\"",
        8: "\"Force et Joie dans la Tempête\"",
        9: "\"Lumière sur le chemin\"",
        10: "« Unis dans l'Esprit »",
        11: "\"Grâces aux Païens!\"",
        12: "\"Libération en Lumière\"",
        13: "\"Paroles de Vie, Lumière des Nations\"",
        14: "\"Levons-nous et marchons !\"",
        15: "\"Unis par Ta Grâce\"",
        16: "\"Guide Nos Pas, Seigneur!\"",
        17: "\"Christ, notre Roi, notre Espérance\"",
        18: "\"Un Peuple Pour Moi\"",
        19: "\"Élevons le Nom de Jésus\"",
        20: "\"Unis dans la Grâce\"",
        21: "\"Unis pour Sa Gloire\"",
        22: "\"Ma Lumière, Mon Sauveur\"",
        23: "\"Prends Courage, Ô Paul!\"",
        24: "\"Liberté dans la Vérité\"",
        25: "\"Dans la Lumière de la Vérité\"",
        26: "\"Lumière de mon cœur\"",
        27: "\"Notre Espoir dans la Tempête\"",
        28: "\"Notre Dieu Fort\"",
    },
    "45": {
        1: "\"Puissance de l'Évangile\"",
        2: "\"À la Lumière de Ta Justice\"",
        3: "\"Par Ta Grâce, Justifiés\"",
        4: "\"Par la Foi, Justifiés\"",
        5: "\"Glorieux Amour de Dieu\"",
        6: "\"Libéré en Christ\"",
        7: "\"Libéré en Christ\"",
        8: "\"Plus Que Vainqueurs dans l'Amour\"",
        9: "\"Fils du Dieu Vivant\"",
        10: "\"Appel à la Foi\"",
        11: "\"Liberté dans ta Grâce\"",
        12: "\"Unis dans l'Amour\"",
        13: "\"Marchons dans Sa Lumière\"",
        14: "\"Unis dans la Foi\"",
        15: "\"Unis dans l'Espérance\"",
        16: "\"Unis dans l'Amour\"",
    },
    "46": {
        1: "\"Unis dans la Croix\"",
        2: "\"Jésus, Notre Sagesse\"",
        3: "\"Croître dans l'Amour\"",
        4: "\"Serviteurs de Ta Grâce\"",
        5: "\"Purifiés par Ta Vérité\"",
        6: "\"Unis dans la Vérité\"",
        7: "\"Unis dans l'Amour\"",
        8: "\"Unis dans l'Amour\"",
        9: "\"Cours vers la Lumière\"",
        10: "\"Unis dans Ta Gloire\"",
        11: "\"Unis dans Sa Grâce\"",
        12: "\"Unis par l'Esprit\"",
        13: "\"Amour Éternel\"",
        14: "\"Édifie Ton Peuple\"",
        15: "\"Victoire en Christ\"",
        16: "\"Unis dans Sa Grâce\"",
    },
    "47": {
        1: "\"Dieu de Consolation\"",
        2: "\"Joie dans la Tristesse\"",
        3: "\"Lettre de Gloire\"",
        4: "\"Lumière dans les Ténèbres\"",
        5: "\"Réconciliés pour l'Éternité\"",
        6: "\"Élargis Nos Cœurs\"",
        7: "\"Dans la Tristesse, Ta Joie\"",
        8: "\"Rayonner par la Générosité\"",
        9: "\"Semons avec Joie\"",
        10: "\"Puissance de l'Obéissance\"",
        11: "\"Dans Ta Lumière, Seigneur\"",
        12: "\"Ma Grâce Te Suffit\"",
        13: "\"Examinez vos cœurs\"",
    },
    "48": {
        1: "« Gloire à Toi, Évangile de Grâce »",
        2: "\"Libérés en Christ\"",
        3: "\"Unis en Christ\"",
        4: "\"Enfants de la Promesse\"",
        5: "\"Libérés par l'Amour\"",
        6: "\"Portons les Fardeaux en Amour\"",
    },
    "49": {
        1: "\"Rédemption en Christ\"",
        2: "\"Riche en Miséricorde\"",
        3: "\"Unis par ta Grâce\"",
        4: "\"Unis en Christ\"",
        5: "\"Lumière dans les Ténèbres\"",
        6: "\"Fortifiés dans le Seigneur\"",
    },
    "50": {
        1: "\"Une Œuvre Parfaite\"",
        2: "\"Élevé au-dessus de tout\"",
        3: "\"À Toi, je renonce\"",
        4: "\"Réjouissez-vous toujours en Lui\"",
    },
    "51": {
        1: "\"Espérance de Gloire\"",
        2: "\"Tout en Toi, notre Lumière\"",
        3: "\"Revêtu de Gloire\"",
        4: "\"Ouvre les Portes de Ta Grâce\"",
    },
    "52": {
        1: "\"Église de Foi, Église d’Espérance\"",
        2: "\"Notre Espérance, Notre Joie\"",
        3: "\"Affermis Nos Cœurs\"",
        4: "\"Ensemble dans l'Espérance\"",
        5: "Enfants de la Lumière",
    },
    "53": {
        1: "\"Espoir Éternel\"",
        2: "\"Dans l'Attente de Ta Gloire\"",
        3: "\"Seigneur, Tu es Fidèle\"",
    },
    "54": {
        1: "\"Au Roi des Siècles, notre Victoire\"",
        2: "\"Un Seul Dieu, Une Seule Voie\"",
        3: "\"Dans Ta Maison, Seigneur\"",
        4: "\"Ferme dans la Foi\"",
        5: "\"Honorons les Sages et les Veuves\"",
        6: "\"Trésor de Foi\"",
    },
    "55": {
        1: "\"Renaître dans Ta Force\"",
        2: "\"Soldat de la Grâce\"",
        3: "\"Dans la Vérité, Nous Tiendrons\"",
        4: "\"Couronne de Justice\"",
    },
    "56": {
        1: "\"Fidèles dans la Lumière\"",
        2: "\"Dans la Grâce du Sauveur\"",
        3: "\"Marchons dans Sa Grâce\"",
    },
    "57": {
        1: "\"Recevoir dans l'Amour\"",
    },
    "58": {
        1: "\"Reflet de Gloire\"",
        2: "\"Couronné de Gloire\"",
        3: "\"Notre Espérance en Jésus\"",
        4: "\"Entrons dans Son Repos\"",
        5: "\"Christ, notre Souverain\"",
        6: "\"Ancre de notre Espoir\"",
        7: "\"Melchisédek, Roi de Paix\"",
        8: "\"Alliance de Grâce\"",
        9: "\"Rédemption Éternelle\"",
        10: "\"Libres par Son Sang\"",
        11: "\"Ensemble dans la Foi\"",
        12: "\"Vers le Trône de Grâce\"",
        13: "\"Dans l'Amour, Nous Sommes Un\"",
    },
    "59": {
        1: "\"Dans la Lumière de Ta Grâce\"",
        2: "\"Agir dans l'Amour\"",
        3: "\"Guide mes Mots, Ô Seigneur\"",
        4: "\"Élève-nous dans Ta Grâce\"",
        5: "\"Patience et Louange\"",
    },
    "60": {
        1: "\"Espérance Éternelle\"",
        2: "Pierre Vivante, Notre Espoir",
        3: "\"Unis dans l'Amour\"",
        4: "\"Portés par Ta Gloire\"",
        5: "\"Le Souverain Pasteur\"",
    },
    "61": {
        1: "\"Notre Lumière, Notre Force\"",
        2: "\"Refuge Éternel\"",
        3: "\"Le Jour du Seigneur\"",
    },
    "62": {
        1: "\"Lumière de Vie\"",
        2: "\"Dans la Lumière de Son Amour\"",
        3: "\"Enfants de l'Amour\"",
        4: "\"Unis dans l'Amour\"",
        5: "\"Triomphe en Christ\"",
    },
    "63": {
        1: "Unis dans la Vérité",
    },
    "64": {
        1: "\"Unis dans la Vérité\"",
    },
    "65": {
        1: "\"Combattons pour la Foi\"",
    },
    "66": {
        1: "\"Révélation de Gloire\"",
        2: "\"Rappelle-moi, Mon Premier Amour\"",
        3: "Réveille nos âmes, Seigneur!",
        4: "\"Saint, Saint, Saint est le Seigneur\"",
        5: "\"L'Agneau Vainqueur\"",
        6: "\"Viens, Ô Agneau de Dieu\"",
        7: "\"Unis dans la Louange\"",
        8: "\"Silence Céleste, Trompettes de Gloire\"",
        9: "\"Dans Ta Puissance, Seigneur\"",
        10: "\"Le Mystère de l'Ange\"",
        11: "\"Le Royaume Est à Notre Roi\"",
        12: "\"Victoire dans le Ciel\"",
        13: "\"Plus Grand que la Bête\"",
        14: "\"Sur la Montagne de Sion\"",
        15: "\"Tes Œuvres Admirables\"",
        16: "\"Justice et Gloire\"",
        17: "\"Roi des Rois, Gloire à l'Agneau\"",
        18: "\"Babylone est Tombée\"",
        19: "\"Alléluia, le Roi des Rois\"",
        20: "\"Règne Éternel\"",
        21: "Jérusalem, Ville de Lumière",
        22: "\"Fleuve de Vie, Lumière Éternelle\"",
    },
};
